---
webServer:
  port: 8086

state:
  filename: ""
  cache:
    releases:
      cacheMinutes: 30
      cacheSize: 3000
    commitTimestamps:
      cacheMinutes: 86400 # 60 days
      cacheSize: 10000

datasources:
  github-releases:
    credentials:
      token: ""
    maxReleases: 0
  github-tags:
    credentials:
      token: ""
    maxReleases: 50
  gitlab-releases:
    credentials:
      token: ""
    maxReleases: 0
  maven:
    credentials:
      token: ""
    maxReleases: 0
  dockerhub:
    credentials:
      token: ""
    maxReleases: 0
